// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for About Page documents */
interface AboutPageDocumentData {
    /**
     * Title field in *About Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about-page.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Content field in *About Page*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about-page.content
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
}
/**
 * About Page document from Prismic
 *
 * - **API ID**: `about-page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutPageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<
    Simplify<AboutPageDocumentData>,
    "about-page",
    Lang
>;
/** Content for Home Page documents */
interface HomePageDocumentData {
    /**
     * Title field in *Home Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home-page.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Subtitle field in *Home Page*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home-page.subtitle
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    subtitle: prismicT.RichTextField;
    /**
     * CTA Text field in *Home Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home-page.ctaText
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    ctaText: prismicT.KeyTextField;
    /**
     * Work Anchor Text field in *Home Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home-page.workAnchorText
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    workAnchorText: prismicT.KeyTextField;
}
/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home-page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home-page",
    Lang
>;
/** Content for Project Tags documents */
interface ProjectTagsDocumentData {
    /**
     * Title field in *Project Tags*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project-tags.Title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    Title: prismicT.KeyTextField;
}
/**
 * Project Tags document from Prismic
 *
 * - **API ID**: `project-tags`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectTagsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<
    Simplify<ProjectTagsDocumentData>,
    "project-tags",
    Lang
>;
/** Content for Project documents */
interface ProjectDocumentData {
    /**
     * Title field in *Project*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Thumbnail field in *Project*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project.thumbnail
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    thumbnail: prismicT.ImageField<never>;
    /**
     * Short Description field in *Project*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.shortDescription
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    shortDescription: prismicT.KeyTextField;
    /**
     * Description field in *Project*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Tags (Comma Separated) field in *Project*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.tags
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    tags: prismicT.KeyTextField;
    /**
     * Sort Order field in *Project*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: project.sortOrder
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    sortOrder: prismicT.NumberField;
    /**
     * Slice Zone field in *Project*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: project.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<ProjectDocumentDataSlicesSlice>;
}
/**
 * Slice for *Project → Slice Zone*
 *
 */
type ProjectDocumentDataSlicesSlice = never;
/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
>;
export type AllDocumentTypes = AboutPageDocument | HomePageDocument | ProjectTagsDocument | ProjectDocument;
/**
 * Default variation for ProjectTagsSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ProjectTagsSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectTagsSliceSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, never>;
/**
 * Slice variation for *ProjectTagsSlice*
 *
 */
type ProjectTagsSliceSliceVariation = ProjectTagsSliceSliceDefault;
/**
 * ProjectTagsSlice Shared Slice
 *
 * - **API ID**: `project_tags_slice`
 * - **Description**: `ProjectTagsSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectTagsSliceSlice = prismicT.SharedSlice<"project_tags_slice", ProjectTagsSliceSliceVariation>;
/**
 * Primary content in TestSlice → Primary
 *
 */
interface TestSliceSliceDefaultPrimary {
    /**
     * Title field in *TestSlice → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: test_slice.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *TestSlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: test_slice.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for TestSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TestSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TestSliceSliceDefault = prismicT.SharedSliceVariation<
    "default",
    Simplify<TestSliceSliceDefaultPrimary>,
    never
>;
/**
 * Slice variation for *TestSlice*
 *
 */
type TestSliceSliceVariation = TestSliceSliceDefault;
/**
 * TestSlice Shared Slice
 *
 * - **API ID**: `test_slice`
 * - **Description**: `TestSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TestSliceSlice = prismicT.SharedSlice<"test_slice", TestSliceSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type {
            AboutPageDocumentData,
            AboutPageDocument,
            HomePageDocumentData,
            HomePageDocument,
            ProjectTagsDocumentData,
            ProjectTagsDocument,
            ProjectDocumentData,
            ProjectDocumentDataSlicesSlice,
            ProjectDocument,
            AllDocumentTypes,
            ProjectTagsSliceSliceDefault,
            ProjectTagsSliceSliceVariation,
            ProjectTagsSliceSlice,
            TestSliceSliceDefaultPrimary,
            TestSliceSliceDefault,
            TestSliceSliceVariation,
            TestSliceSlice,
        };
    }
}
