// This file is generated by Slice Machine. Update with care!

import ProjectTagsSlice from './ProjectTagsSlice';
import TestSlice from './TestSlice';

export {
	ProjectTagsSlice,
	TestSlice,
};

export const components = {
	project_tags_slice: ProjectTagsSlice,
	test_slice: TestSlice,
};
